version: "3"

services:
  employee-db:
    image: mariadb:10.2.21
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=employee-db
    command: mysqld --lower_case_table_names=1
    ports:
      - "3306:3306"