logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/employee-db
    username: root
    password: root
  flyway:
    table: schema_version
    locations: classpath:db/migration